test_ratio: 0.2
target_column: "Retard mensuel moyen à l'arrivée des vols exploités par la Cie sur la relation (min)"

param_space:
  num_leaves:
    _target_: hyperopt.hp.choice
    args:
      - "num_leaves"
      - [20, 30, 40, 50]
  max_depth:
    _target_: hyperopt.hp.choice
    args:
      - "max_depth"
      - [5, 10, 15]
  learning_rate:
    _target_: hyperopt.hp.uniform
    args:
      - "learning_rate"
      - 0.01
      - 0.1
  n_estimators:
    _target_: hyperopt.hp.choice
    args:
      - "n_estimators"
      - [50, 100, 200]


automl_max_evals: 100


gcp_project_id: "gen-lang-client-0456101191"


primary_csv_path: "data/03_primary/primary.csv"


gcs_primary_folder: "retard-avion-data/primary/data"

partition_chunk_size: 1000


mlflow_enabled: True # Do we log metrics and artifacts to MLflow ?
mlflow_experiment_id: 1 # Experimented ID associated to this project

# MLflow
log_to_mlflow: true                # active/désactive le tracking

mlflow_server_uri: "http://127.0.0.1:5000/" 


experiment_id: "retard_avion_experiment"
