test_ratio: 0.2

# conf/base/parameters.yml

param_space:
  num_leaves:
    _target_: hyperopt.hp.choice
    args:
      - "num_leaves"
      - [20, 30, 40, 50]
  max_depth:
    _target_: hyperopt.hp.choice
    args:
      - "max_depth"
      - [5, 10, 15]
  learning_rate:
    _target_: hyperopt.hp.uniform
    args:
      - "learning_rate"
      - 0.01
      - 0.1
  n_estimators:
    _target_: hyperopt.hp.choice
    args:
      - "n_estimators"
      - [50, 100, 200]
# Ajoutez ceci à côté de param_space
automl_max_evals: 10


# conf/base/parameters.yml

# Votre projet GCP
gcp_project_id: "gen-lang-client-0456101191"



# chemin local vers primary.csv
primary_csv_path: "data/03_primary/primary.csv"

# dossier où seront écrits les partitions
# ici on réutilise le même paramètre que pour la suite
gcs_primary_folder: "retard-avion-data/primary/data"


# taille de chaque partition (nombre de lignes)
partition_chunk_size: 1000

